# This example demonstrates a Rollout using the blue-green update strategy, which contains a manual
# gate before promoting the new stack.
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: nginx:1.19-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - analysis:
          templates:
          - templateName: sleep-job
          args:
          - name: duration
            value: 1h

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
spec:
  selector:
    app: rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
